### ISSUE TITLE
docker部署失败

### ISSUE THREAD

**Issue by ghost** [chancelyg/syncmemo#1]
可能配置文件有问题

**Comment by chancelyg** [comment]
有具体的报错信息？

**Comment by chancelyg** [comment]
如果报错输出如下
```docker
Step 9/13 : COPY --from=compile-python /usr/local/python3.9.1 /usr/local/python3.9.1
 ---> 561431e075dc
Step 10/13 : COPY --from=compile-python /app/syncmemo /app/syncmemo
 ---> a4a9e0c0e271
Step 11/13 : COPY app.conf /app/syncmemo/conf/app.conf
COPY failed: file not found in build context or excluded by .dockerignore: stat app.conf: file does not exist
```
需要在编译Docker镜像的目录下增加 app.conf文件，格式参考仓库 **conf/app.conf.example** 文件

**Comment by ghost** [comment]
镜像可以生成，但是容器生成后，访问http://127.0.0.1:7900/，无法进入主页

**Comment by jxzzlfh** [comment]
配置文件：
[general]
HOST = 127.0.0.1
PORT = 7900
DEBUG = 1
SITE_NAME = syncmemo
SITE_URL = http://127.0.0.1

[memo]
# 允许便签最大大小
MEMO_MAX_SIZE = 5
# 便签保存间隔
SAVE_SPANTIME = 5000
# 便签ID长度
MEMO_ID_LENGTH = 4
LOCAL_STORE_LENGTH = 10

[log]
PATH = running.log
LEVEL = INFO

[store]
PATH = data/cache
TIMEOUT_DAY = 30

**Comment by chancelyg** [comment]
app.conf中的HOST填入0.0.0.0，Port填入7900即可，已重新更新README文档

**Comment by ghost** [comment]
> app.conf中的HOST填入0.0.0.0，Port填入7900即可，已重新更新README文档
dockers部署成功
