### ISSUE TITLE
ImportError: cannot import name 'app' from 'flaskr' (/app/syncmemo/src/flaskr/init.py)

### ISSUE THREAD

**Issue by mS0gxokXEsg5ysJ7J79kzWiqO1fHgFA6ZR8eEls** [chancelyg/syncmemo#3]
启动不了 显示这个

Traceback (most recent call last):
  File "/app/syncmemo/src/main.py", line 1, in <module>
    from flaskr import app
ImportError: cannot import name 'app' from 'flaskr' (/app/syncmemo/src/flaskr/__init__.py)

**Comment by leihuazhe** [comment]
使用4.11的那版提交，作者新的提交，按照 readme 跑不通，需要修改。

**Comment by mS0gxokXEsg5ysJ7J79kzWiqO1fHgFA6ZR8eEls** [comment]
> 使用4.11的那版提交，作者新的提交，按照 readme 跑不通，需要修改。

算了  不折腾这个了  我找了个 Docker，一键启动，真●香；
缺点是无法持久化，重启后数据会初始化自动灰飞烟灭，
不过作为临时中转站问题不大，而且 NAS+UPS 几乎从来不重启~

#-------------------------代码如下：
docker run -dit \
  -p 80:80 \
  --name NotePad \
  --hostname NotePad \
  --restart unless-stopped \
  okss/notepad:1

**Comment by chancelyg** [comment]
更新了下README，按照目前README的方法跑Docker是没问题的，可以试一下
