### ISSUE TITLE
有时间可以写一下数据备份方式到readme上吗

### ISSUE THREAD

**Issue by 2beetle** [chancelyg/syncmemo#4]
docker部署在vps 想定时备份一下到本地防止数据丢失

**Comment by chancelyg** [comment]
OK，稍后更新下

**Comment by chancelyg** [comment]
我把之前的代码更新上来了，换了界面，算是2.0版本了，把保存数据的方法也写入了 README.md 中，可以试用一下

但很可惜之前的数据我服务器上都没有了，如果你有一些旧版本测试数据借我看看我的话我可以帮忙写个脚本迁移到新的版本上

**Comment by 2beetle** [comment]
> 我把之前的代码更新上来了，换了界面，算是2.0版本了，把保存数据的方法也写入了 README.md 中，可以试用一下
> 
> 但很可惜之前的数据我服务器上都没有了，如果你有一些旧版本测试数据借我看看我的话我可以帮忙写个脚本迁移到新的版本上

我怎么给你

**Comment by 2beetle** [comment]
> 我把之前的代码更新上来了，换了界面，算是2.0版本了，把保存数据的方法也写入了 README.md 中，可以试用一下
> 
> 但很可惜之前的数据我服务器上都没有了，如果你有一些旧版本测试数据借我看看我的话我可以帮忙写个脚本迁移到新的版本上

http://minio.beocean.net/api/v1/download-shared-object/aHR0cDovLzEyNy4wLjAuMTo5MDAwL21lZGlhL2JlL29sZF9kYXRhLnRhci5nej9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUxMSzdMNUIwR1NPMFFVNVNISkE0JTJGMjAyNDExMjYlMkZjbi1ndWFuZ3pob3UlMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI2VDA4MzgxMFomWC1BbXotRXhwaXJlcz00MzIwMCZYLUFtei1TZWN1cml0eS1Ub2tlbj1leUpoYkdjaU9pSklVelV4TWlJc0luUjVjQ0k2SWtwWFZDSjkuZXlKaFkyTmxjM05MWlhraU9pSk1URXMzVERWQ01FZFRUekJSVlRWVFNFcEJOQ0lzSW1WNGNDSTZNVGN6TWpZeU5qVTFOeXdpY0dGeVpXNTBJam9pWW1WdlkyVmhiaUo5Lm4wSTRDSUpiUThkNjBFSVZGN3FIOE9MQXBRdWRVNHBfb3Bqdmk2Z2dDemc3NElEUENldHFDSDJLX2ZFT2Z3Y3dvV1JFaklTZG5nanlRb0dKam1CTlJ3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZ2ZXJzaW9uSWQ9bnVsbCZYLUFtei1TaWduYXR1cmU9ODg1MmYyZTVlNWVlNzI2M2FkMDIzMGQxMDZjNWU5YmY5MjA2YjNhZmQwMGJjNDE5ZmJiOTc1ZjFiYzdlZDQ0YQ

**Comment by chancelyg** [comment]
将之前的数据目录压缩成zip目录发我邮箱：ycs1026@vip.qq.com

**Comment by 2beetle** [comment]
> 我把之前的代码更新上来了，换了界面，算是2.0版本了，把保存数据的方法也写入了 README.md 中，可以试用一下
> 
> 但很可惜之前的数据我服务器上都没有了，如果你有一些旧版本测试数据借我看看我的话我可以帮忙写个脚本迁移到新的版本上

[old_data.tar.gz](https://github.com/user-attachments/files/17916486/old_data.tar.gz)

**Comment by 2beetle** [comment]
> 我把之前的代码更新上来了，换了界面，算是2.0版本了，把保存数据的方法也写入了 README.md 中，可以试用一下
> 
> 但很可惜之前的数据我服务器上都没有了，如果你有一些旧版本测试数据借我看看我的话我可以帮忙写个脚本迁移到新的版本上

已经把压缩包发你邮箱了 cache目录下的数据

**Comment by chancelyg** [comment]
迁移到问题可能无解，因为旧版本的缓存 Flask-caching 无法遍历输出，试了挺多办法的都无效

旧版本的数据是设置了过期时间的，可能手动复制过来新版本反而会快一些

**Comment by 2beetle** [comment]
> 迁移到问题可能无解，因为旧版本的缓存 Flask-caching 无法遍历输出，试了挺多办法的都无效
> 
> 旧版本的数据是设置了过期时间的，可能手动复制过来新版本反而会快一些

好的
